language: php
php:
  - '7.0'
  - '7.1'
before_script:
  - phpenv config-rm xdebug.ini
  - composer install --prefer-dist --no-progress --no-interaction
  - php artisan config:cache --env=testing
script: php vendor/bin/codecept run